In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 29 11:48:53 2023
Web Scraper to double check all addresses with Canada Post

For Dying with Dignity
@author: nigel
"""
import pandas as pd
import numpy as np
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException

from selenium.common.exceptions import TimeoutException



""" Pull CSV file"""

File_Name  =   "Test Sheet-NC.xlsx" ##"Nigel Cheriyan Address Cleanup.xlsx"
Rest_Excel = pd.read_excel(File_Name, sheet_name='Database cleanup Pulled 10 2023',na_values ='NaN').iloc[:,9:]
Excel_Sheet = pd.read_excel(File_Name, sheet_name='Database cleanup Pulled 10 2023',na_values ='NaN').iloc[:,0:9]# pull data from file


""" Create search input function """

def Search_Input(Row):
    Url_Row = Row[0:8].dropna()
    Unjoined_Search = Url_Row.to_string(header=False,index=False).split('\n')
    Joined_Search = ' '.join(Unjoined_Search)
    return Joined_Search

""" Pull up Website ~~~ CODE FROM CAN POST API ADDRESS COMPLETE"""
#Key,SearchTerm, LastId, SearchFor , Country, LanguagePreference, MaxSuggestions, MaxResults, Origin, Bias, Filters, GeoFence


Url = "https://www.canadapost-postescanada.ca/ac/support/api/addresscomplete-interactive-find/"

Driver = webdriver.Chrome()

Driver.get(Url)

Search_Bar_Position = '//*[@id="tryitnow"]/div/div/div/div/div/section[1]/div/table/tbody/tr[1]/td[2]/input'
Country_Position = '//*[@id="tryitnow"]/div/div/div/div/div/section[1]/div/table/tbody/tr[3]/td[2]/input'
Enter_Position  = '//*[@id="btnTest"]'
Address_Position = '//*[@id="pnlResults"]/table/tbody/tr/td[2]'
Description_Position = '//*[@id="pnlResults"]/table/tbody/tr/td[5]'
Second_Position = '//*[@id="pnlResults"]/table/tbody/tr[2]/td[2]'

Error_Position = '//*[@id="pnlError"]/table/tbody/tr/td[2]'


"""function to write in country """
def Country_Search(Country):
    C_Search = Driver.find_element(By.XPATH,Country_Position)
    C_Search.clear()
    C_Search.send_keys(Country)

"""function to get data"""
Descriptions = []
def Get_Address(Joined_Search):
    Locate_Search = Driver.find_element(By.XPATH, Search_Bar_Position)
    Locate_Search.clear()
    Locate_Search.send_keys(Joined_Search)
    Locate_Enter = Driver.find_element(By.XPATH, Enter_Position)
    Locate_Enter.click()
    try:
        WebDriverWait(Driver, 5).until(EC.presence_of_element_located((By.XPATH, Address_Position)))
    except TimeoutException:
        return None
    else:
        try:
            Driver.find_element(By.XPATH,Error_Position)
        except NoSuchElementException:
            try:
                Driver.find_element(By.XPATH,Second_Position)
            except NoSuchElementException:
                Address_Output = Driver.find_element(By.XPATH, Address_Position)
                Address = Address_Output.text
                Description_Output = Driver.find_element(By.XPATH, Description_Position)
                Description = Description_Output.text
                Descriptions.append(Description)
                if Description[-9:-1] == 'Addresse':
                    return None
                else:
                    return Address, Description
            else:
                return None
        else:
            return None




""" Parse String Format for associated country"""
def Parse_String_CAN(Address,Description):
    Split_Description = Description.split(',')
    City = Split_Description[0]
    Province = Split_Description[1]
    Postal_Code = Split_Description[2]
    Success = [Address,'','','','',City,Province,Postal_Code,'Canada','Yes']
    return Success




def Parse_String_Non_CAN(Address, Description):
        if Country == 'United States' or 'USA':
            Split_Description = Description.split(' ')
            City = Split_Description[0]
            Province = Split_Description[1]
            Postal_Code = str(Split_Description[2])
            Success = [Address,'','','','',City,Province,Postal_Code,Country,'Yes']

        if Country == 'Australia':
            Split_Description = Address.split(',')
            Address = Split_Description[0]
            Split_Description = Split_Description[1].split(' ')
            City = Split_Description[0]
            Province = Split_Description[1]
            Postal_Code = Split_Description[2]
            Success =  [Address,'','','','',City,Province,Postal_Code,Country,'Yes']
        if Country in ['United Kingdom','England','UK','Belgium']:
            Split_Description = Description.split(',')
            City = Split_Description[0]
            Postal_Code = Split_Description[1]
            Success = [Address,'','','','',City,'',Postal_Code,Country,'Yes']
            return
        else:
            Split_Description = Description.split(' ')
            City = Split_Description[0]
            Postal_Code = Split_Description[1]
            Success =  [Address,'','','','',City,'',Postal_Code,Country,'Yes']

        return Success
""" function for what to do if info was NOT found on Canada Post website"""

def Unsuccessful(Row):
    row_unsuccessful = Row
    row_unsuccessful['Successful'] =  'No'
    return row_unsuccessful

"""Highlighting Function"""

def rowStyle(row):
    if row['Successful'] == 'Yes':
        print('Highlight Green')
        return ['background-color: green'] * len(row)
    return [''] * len(row)


""" function for checking if data fits properly into array"""


def Index_Input_CAN(results):
        if results != None:
            try:
                return Parse_String_CAN(results[0],results[1])
            except IndexError:
                print('There was an Index Error')
                return Unsuccessful(Row)
        else:
            return Unsuccessful(Row)

def Index_Input_Non_CAN(results):
        if results != None:
            try:
                return Parse_String_Non_CAN(results[0],results[1])
            except IndexError:
                print('There was an Index Error')
                return Unsuccessful(Row)
        else:
            return Unsuccessful(Row)

    

"""Loop across all the clientel and check address"""
Header = Excel_Sheet.columns.ravel()
Header = np.append(Header, 'Successful')
Fixed_Sheet_Data_CAN = pd.DataFrame([],columns = Header)
Fixed_Sheet_Data_Non_CAN = pd.DataFrame([],columns = Header)
Excel_Sheet_CAN = Excel_Sheet.loc[Excel_Sheet['PREFERRED ADDRESS LINE COUNTRY'] == 'Canada']
Excel_Sheet_Non_CAN = Excel_Sheet.loc[Excel_Sheet['PREFERRED ADDRESS LINE COUNTRY'] != 'Canada']



for Index, Row in Excel_Sheet_CAN.iterrows():
    print(Index)
    Search = Search_Input(Row)
    Fixed_Sheet_Data_CAN.loc[Index] = Unsuccessful(Row)
    if Search != 'Series([], )':
        results = Get_Address(Search)
        New_Address = Index_Input_CAN(results)
        if New_Address[-1]== 'No':
            Search = Row['PREFERRED ADDRESS LINE 1']
            print(Search)
            results = Get_Address(Search)
            New_Address = Index_Input_CAN(results)

            if New_Address[-1]== 'No':
                print('Moving on')
            else:
                if New_Address[7] == Row['PREFERRED ADDRESS POSTAL CODE']:
                    print(New_Address)
                    Fixed_Sheet_Data_CAN.loc[Index] = New_Address
                else:
                    print( "Blah")
        else:
            Fixed_Sheet_Data_CAN.loc[Index] = New_Address

for Index, Row in Excel_Sheet_Non_CAN.iterrows():
    print(Index)
    Search = Search_Input(Row)
    Fixed_Sheet_Data_Non_CAN.loc[Index] = Unsuccessful(Row)
    if Search != 'Series([], )':
        Country = Row['PREFERRED ADDRESS LINE COUNTRY']
        Country_Search(Country)
        results = Get_Address(Search)
        New_Address = Index_Input_Non_CAN(results)
        if New_Address[-1] == 'No':
            Search = Row['PREFERRED ADDRESS LINE 1']
            results = Get_Address(Search)
            New_Address = Index_Input_Non_CAN(results)

        else:
            Fixed_Sheet_Data_Non_CAN.loc[Index] = New_Address



# if no postal code and no address , move on


Driver.quit()

Fixed_Sheet_Data = pd.concat([Fixed_Sheet_Data_CAN,Fixed_Sheet_Data_Non_CAN], axis = 0)
Fixed_Sheet_Data.sort_index(inplace = True)
Full_Sheet = pd.concat([Fixed_Sheet_Data,Rest_Excel],axis = 1)
Full_Sheet.style.apply(rowStyle,axis = 1).drop('Successful').to_excel('Cleaned_Excel_Sheet__back_DWDC.xlsx', index = False)

C:\Users\nigel\AppData\Local\Temp\ipykernel_19780\2360780955.py:183: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  Header = Excel_Sheet.columns.ravel()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
17
18
19
20
21
22
23
24
25
16
      PREFERRED ADDRESS LINE 1 PREFERRED ADDRESS LINE 2  \
0                          NaN                      NaN
1               57 Bassett Ave
2               6 Reid's Ridge
3      78-50220 Range Road 202
4         2104 Auburn Ridge Dr
5              10925 86 Ave NW
6          9386 Martin Park Dr
7            13 Cornerstone Dr
8       809-322 Eglinton Ave E
9            17-80 Rue Manseau
10     1009-123 Eglinton Ave E
11        811-19 Woodlawn Rd E
12          515-16 Rosedale Rd
13               207 Albert St
14               207 Albert St
15         1001-456 Moberly Rd
16                PO Box 10071
17   154 Strathmore Lakes Bend
18             1522 Gregory Rd
19             518 Nassau Cres
20  1308-950 Arbour Lake Rd NW
21           2134 Thomson Cres
22                 288 Haig St
23              217-205 1st St
24         1607-1 Evergreen Pl
25              3911 Route 102

   PREFERRED ADDRESS LINE 3 PREFERRED ADDRESS LINE 4 PREFERRED ADDRESS LINE 5  \
0                       NaN                      NaN                      NaN
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25

   PREFERRED ADDRESS LINE  CITY PREFERRED ADDRESS PROVINCE  \
0                           NaN                        NaN
1                 Richmond Hill                         ON
2                   Oro-Medonte                         ON
3                 Beaver County                         AB
4                       Orl√©ans                         ON
5                      Edmonton                         AB
6                   Black Creek                         BC
7                  Stoney Creek                         ON
8                       Toronto                         ON
9                 Drummondville                         QC
10                      Toronto                         ON
11                       Guelph                         ON
12                      Toronto                         ON
13                    Stratford                         ON
14                    Stratford                         ON
15                    Vancouver                         BC
16                  Tallahassee
17                   Strathmore                         AB
18                 West Kelowna                         BC
19                       Sarnia                         ON
20                      Calgary                         AB
21                       Severn                         ON
22                       Oshawa                         ON
23                    Courtenay                         BC
24                     Winnipeg                         MB
25                  Island View                         NB

   PREFERRED ADDRESS POSTAL CODE PREFERRED ADDRESS LINE COUNTRY Successful  \
0                            NaN                         Canada         No
1                        L4B 4J9                         Canada        Yes
2                        L0K 1N0                         Canada        Yes
3                        T0B 4J2                         Canada        Yes
4                        K1W 1J1                         Canada        Yes
5                        T6G 0W8                         Canada        Yes
6                        V9J 1C4                         Canada        Yes
7                        L8J 0A1                         Canada        Yes
8                        M4P 1L6                         Canada        Yes
9                        J2B 5Z7                         Canada        Yes
10                       M4P 1J2                         Canada        Yes
11                       N1H 7B1                         Canada        Yes
12                       M4W 2P4                         Canada        Yes
13                       N5A 3K7                         Canada        Yes
14                       N5A 3K7                         Canada        Yes
15                       V5Z 4L7                         Canada        Yes
16                            FL                  United States        Yes
17                       T1P 1Y8                         Canada        Yes
18                       V4T 2R2                         Canada        Yes
19                       N7S 4H9                         Canada        Yes
20                       T3G 5B3                         Canada        Yes
21                       L3V 0V7                         Canada        Yes
22                       L1G 5N8                         Canada        Yes
23                       V9N 1A5                         Canada        Yes
24                       R3L 0E9                         Canada        Yes
25                       E3E 1H1                         Canada        Yes

    ...  MAILING SALUTATION FOR ORGANIZATION DECCRIPTION  \
0   ...                                              NaN
1   ...                                              NaN
2   ...                                              NaN
3   ...                                              NaN
4   ...                                              NaN
5   ...                                              NaN
6   ...                                              NaN
7   ...                                              NaN
8   ...                                              NaN
9   ...                                              NaN
10  ...                                              NaN
11  ...                                              NaN
12  ...                                              NaN
13  ...                                              NaN
14  ...                                              NaN
15  ...                                              NaN
16  ...               Friends at Final Exit Network Inc.
17  ...                                              NaN
18  ...                                              NaN
19  ...                                              NaN
20  ...                                              NaN
21  ...                                              NaN
22  ...                                              NaN
23  ...                                              NaN
24  ...                                              NaN
25  ...                                              NaN

   MAILING SALUTATION FOR ORGANIZATION IMPORT ID  CnRelInd_1_01_Name  \
0                                            NaN                 NaN
1                                            NaN                 NaN
2                                            NaN                 NaN
3                                            NaN                 NaN
4                                            NaN                 NaN
5                                            NaN                 NaN
6                                            NaN                 NaN
7                                            NaN                 NaN
8                                            NaN                 NaN
9                                            NaN                 NaN
10                                           NaN                 NaN
11                                           NaN                 NaN
12                                           NaN    Margaret Bentham
13                                           NaN      Patricia Reavy
14                                           NaN        Denis Beatty
15                                           NaN    Michael MacNeill
16                          00001-528-0000041279                 NaN
17                                           NaN       Patricia Clay
18                                           NaN                 NaN
19                                           NaN                 NaN
20                                           NaN                 NaN
21                                           NaN                 NaN
22                                           NaN                 NaN
23                                           NaN                 NaN
24                                           NaN                 NaN
25                                           NaN                 NaN

    CnRelInd_1_01_Import_ID CnRelInd_1_02_Name  CnRelInd_1_02_Import_ID  \
0                       NaN                NaN                      NaN
1                       NaN                NaN                      NaN
2                       NaN                NaN                      NaN
3                       NaN                NaN                      NaN
4                       NaN                NaN                      NaN
5                       NaN                NaN                      NaN
6                       NaN                NaN                      NaN
7                       NaN                NaN                      NaN
8                       NaN                NaN                      NaN
9                       NaN                NaN                      NaN
10                      NaN                NaN                      NaN
11                      NaN                NaN                      NaN
12     20797-033-0000004506    Sheilagh Hickie     20797-033-0000004603
13     20797-033-0000001120                NaN                      NaN
14     20797-033-0000001121                NaN                      NaN
15     20797-033-0000003974                NaN                      NaN
16                      NaN                NaN                      NaN
17     20797-033-0000006414                NaN                      NaN
18                      NaN                NaN                      NaN
19                      NaN                NaN                      NaN
20                      NaN                NaN                      NaN
21                      NaN                NaN                      NaN
22                      NaN                NaN                      NaN
23                      NaN                NaN                      NaN
24                      NaN                NaN                      NaN
25                      NaN                NaN                      NaN

    CnRelInd_1_03_Name CnRelInd_1_03_Import_ID CnRelInd_1_04_Name  \
0                  NaN                     NaN                NaN
1                  NaN                     NaN                NaN
2                  NaN                     NaN                NaN
3                  NaN                     NaN                NaN
4                  NaN                     NaN                NaN
5                  NaN                     NaN                NaN
6                  NaN                     NaN                NaN
7                  NaN                     NaN                NaN
8                  NaN                     NaN                NaN
9                  NaN                     NaN                NaN
10                 NaN                     NaN                NaN
11                 NaN                     NaN                NaN
12                 NaN                     NaN                NaN
13                 NaN                     NaN                NaN
14                 NaN                     NaN                NaN
15                 NaN                     NaN                NaN
16                 NaN                     NaN                NaN
17                 NaN                     NaN                NaN
18                 NaN                     NaN                NaN
19                 NaN                     NaN                NaN
20                 NaN                     NaN                NaN
21                 NaN                     NaN                NaN
22                 NaN                     NaN                NaN
23                 NaN                     NaN                NaN
24                 NaN                     NaN                NaN
25                 NaN                     NaN                NaN

    CnRelInd_1_04_Import_ID
0                       NaN
1                       NaN
2                       NaN
3                       NaN
4                       NaN
5                       NaN
6                       NaN
7                       NaN
8                       NaN
9                       NaN
10                      NaN
11                      NaN
12                      NaN
13                      NaN
14                      NaN
15                      NaN
16                      NaN
17                      NaN
18                      NaN
19                      NaN
20                      NaN
21                      NaN
22                      NaN
23                      NaN
24                      NaN
25                      NaN

[26 rows x 125 columns]

In [4]:
Full_Sheet.style.apply(rowStyle,axis = 1)

Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green

In [7]:
Full_Sheet.style

In [12]:
(Full_Sheet.style.apply(rowStyle,axis = 1)).to_excel('Cleaned_Excel_Sheet__back_DWDC.xlsx', index = False)

Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green
Highlight Green

AttributeError: 'Styler' object has no attribute 'drop'